# Generated by Django 5.1.4 on 2024-12-22 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_userprofile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='name',
        ),
    ]
