# Generated by Django 5.1.4 on 2024-12-22 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_remove_userprofile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='roll_no',
            field=models.CharField(max_length=100),
        ),
    ]
