# Generated by Django 5.1.4 on 2024-12-26 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_alter_userprofile_roll_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='hackerrank',
            new_name='geeksforgeeks',
        ),
    ]
